services:
  - type: web
    name: taskflow-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true&connection_limit=1
      - key: DATABASE_USERNAME
        value: postgres.kucmquncubtheipkzzke
      - key: DATABASE_PASSWORD
        value: "" # Set the real password in Render dashboard as a secret, do not commit it
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://taskmanager-lac-alpha-73.vercel.app
      - key: DDL_AUTO
        value: update
      - key: LOG_LEVEL
        value: INFO
