services:
  - type: web
    name: taskflow-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://db.kucmquncubtheipkzzke.supabase.co:5432/postgres?sslmode=require
      - key: DATABASE_USERNAME
        value: postgres
      - key: DATABASE_PASSWORD
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://taskflow-XXXX.vercel.app
      - key: DDL_AUTO
        value: update
      - key: LOG_LEVEL
        value: INFO
