#for using local also and prod also 
DATABASE_URL=jdbc:postgresql://{db_host}.supabase.co:5432/postgres?sslmode=require
DATABASE_USERNAME=DB username
DATABASE_PASSWORD=DB pass

# GEMINI API
gemini.api.key= Enter Your Gemini Key here

